language: node_js
node_js:
  - "node"
  - "lts/*"
  - "8"
  - "10"
services:
  - mongodb
before_script:
  - make build
script:
  - make lint
  - make test
  - until nc -z localhost 27017; do echo Waiting for MongoDB; sleep 1; done; sleep 1
  - make integration-test
